### ISSUE TITLE
Syntax handler

### ISSUE THREAD

**Issue by VictorCarri** [PatrickDuncan/cleansio#100]
Add a module which generates derived forms of English roots (nouns, verbs, adjectives, etc.) so that we don't have to store them separately in our list of explicit files.

Eg. instead of storing "f***, "f***er", "f***ed", "f***ing", "f***s", "f***y", etc. separately - store just the word "f***", and have a module try each combination of root+suffix while censoring.

**Comment by PatrickDuncan** [comment]
1. We don't have time
2. Overly complex and doesn't solve an issue, it is cool however!
3. It increases the time of execution
4. The amount of space to store the word variants is trivial (< 5 KB)
5. More volatile than a static list

Closing for now
