### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by PatrickDuncan** [PatrickDuncan/cleansio#21]
We need a logo for our project.

**Comment by richardbmx** [comment]
@PatrickDuncan  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by PatrickDuncan** [comment]
Hi @richardbmx, we would love to see what you can do. We would like the logo to have a few things:
1. The project's name: Cleansio
2. Audio imagery
3. Censorship imagery
4. [Google Colours](https://material.io/design/color/#tools-for-picking-colors)
5. 2:1 aspect ratio

Please send the email to cleanseaudio@gmail.com. Thank you!

**Comment by richardbmx** [comment]
@PatrickDuncan  perfect what do you mean with  Censorship imagery ?

**Comment by PatrickDuncan** [comment]
> @PatrickDuncan perfect what do you mean with Censorship imagery ?

We're trying to remove swear words from music so we want imagery to represent that. Something like this @levin-noro http://solewhat.com/6673-big_default/monkey-hear-no-evil-pin.jpg

**Comment by richardbmx** [comment]
@PatrickDuncan  Ok perfect I'm going to work on it

**Comment by richardbmx** [comment]
I present this first proposal based on what you have indicated, I will work on other models so that you have different options to select

![logo110](https://user-images.githubusercontent.com/35604837/46819610-2f565700-cd52-11e8-9616-1b83b599780c.png)

**Comment by richardbmx** [comment]
This is a second model

![logo11022](https://user-images.githubusercontent.com/35604837/46823832-3cc50e80-cd5d-11e8-942a-943ec362894f.png)

**Comment by PatrickDuncan** [comment]
Thanks @richardbmx. I like them, I'm just waiting to hear back from my teammates before confirming.

How would you like to accredited?

**Comment by PatrickDuncan** [comment]
Hey @richardbmx my teammates chose the last one. Can you please ensure the white background ones are transparent?

We will definitely add you to the readme!

**Comment by richardbmx** [comment]
@PatrickDuncan  Perfect inside the folder will be the logo in PNG format that is transparent, in a moment I send you the link of the google folder

**Comment by richardbmx** [comment]
@PatrickDuncan  Here I give you the link with all the necessary files to use the logo, inside you find different variations of the logo to be used in different applications as well as the original files to edit them if you need it. Any questions you can write me I am ready for next projects if you wish...

[Google Drive](https://drive.google.com/open?id=1BMNK5H6K0lY--bvSbu0VKWuQ4Ipewm8E)

**Comment by PatrickDuncan** [comment]
Thanks @richardbmx, check out #32

**Comment by richardbmx** [comment]
@PatrickDuncan  It was a pleasure to work with you
