### ISSUE TITLE
Behaviour Diagram

### ISSUE THREAD

**Issue by PatrickDuncan** [PatrickDuncan/cleansio#36]
I would like a detailed diagram of the main actions as of c5d310f5f75e4e2f402e0d939992a95195573a9c. It would help greatly when new teammates are added to our project.

Please use https://draw.io and make it open for extension.

**Comment by VictorCarri** [comment]
**Public Link:** 
https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=App%20Flowchart#R3Vxbd5s4EP41Pts%2BJMeAuPgxcdI0e9o0W6fb5qmHGMXmLAYfwLn0168EyIYZuSYuSInzEjMGGebyaeYbiYE1XjxdpP5y%2FjkJaDQwh8HTwDobmOzPttg%2FLnkuJa47KgWzNAxKkbERTMJftBIOK%2BkqDGjWODFPkigPl03hNIljOs0bMj9Nk8fmafdJ1PzVpT%2BjSDCZ%2BhGWfg%2BDfF5KPdPdyD%2FScDYXv2w41fMtfHFy9STZ3A%2BSx5rIOh9Y4zRJ8vLT4mlMI648oZfyug9bvl3fWErjvM0Ff8%2BPEnJxfXFye%2FX9n8vJj4sH1zmqRnnwo1X1wP%2F6URj4OeVXxstVXt18%2Fiw0kiarOKB80OHAOn2chzmdLP0p%2F%2FaR%2BQCTzfNFxI4M9rEanqY5fdp638ZaG8yNaLKgefrMTqkuOFpr8Fm4RnX8uDHIWjavGUNc51c%2BMFuPvVET%2B1Bp6gVaM5HWLktVcRG%2F8gPW2jxZ3K0yNRrzmgrzbKQvT6Iuuy91EaQupB4aByc8WtnRNPKzLJw2tcKePH3%2BUflccXDLD47ttcZogAIZ6Ishh5%2FOaL7LsFivNcXZv1FcSiM%2FDx%2BatyHTZvUL10kY5zWzGdDRDWCRLFmlU1pdVg91NJILRnLASKUm0EiFedcPvr%2FFbWTx67S8Q8qsnHJ4pFnGoZfdUhxw%2BVOoH2psEDcSnDEl9ofK7SxwnH4Dh%2Bv8hziPfd4npEqX3I2VO0PP1hp6cI4x32zouchnrhLkNSxE8qafZHma%2FEfHScSi0zqLk5ideXofRhEQsfltFnNnY45AmfyUB1zI8qWT6otFGAT8Z6Th2gzoP4nYSrsjHKJEZSbgIW3fpH6cTdPwrsC2VRAmPO0MmUp0o9vROkkSrtkW4Ky%2B1DfqEuBKTNtA3NCyhOCapiG7Y%2B6wJRBWyLfBwduGnpUin6cV%2BbwtPvFi4LPAQNBpesY9Adg1X7plhePhIZ%2FQNwH6tjVDoSHLVpyIa%2FuOfZjlxXOXghUUhELwic4oTwhLMbuREJ7KZOhyJqv9xqGafGQ0TS6xuKMSvQ2cayDlZ3N%2FyT%2FeR%2FSpwvHTXZDeFoN1YaYHMRNquC1mjsCEPFIMmTh7mazumNvmYcyzl2nC3D7ODxhERzBZl1BLakEUZ0STKJxya%2BRznFEOmWfwI%2Fsoo8xavJDO6GwhNZrqdHNbYlFPNi2JbklfujVlPBQZf%2Fv69fzq5uf1l8nlzeWXq0KpNUUzz6b%2BYsAt7vgLrqZyxuHXD99FNH7HBjn5dnb55efk5uv5yef3R0ww%2BXQ5Pv%2F56fzq4ubje918oAm9nGBTWIbEFOtw6N4WeOpoFE7Un865wirfLyxSBoAQ%2BWnqP782J7c9cozJVsVujiHkIBmAdYsJMDcjbAClEC6MXdP%2FmEFI0VHxCxxpoMMGuaMknm0cfFzYy2eqLaR%2BXl66Da6q4KjASnNUWA6wiSvBfmJjo7i9GQU3uk6CAIFKMZmWoijMuMqTe%2FG1%2FhnVcuyGWi1JY8ewJGrtrQKwzJZT6sCsZkzg%2Fa9Op8TWrtMu2mVrfsscOg123xVfQ0ps0LLoakN8EbnK1VRncE5GVVXb6ozZvRluipl8C3fR%2FsARINFZ400J8erM6dHweEi2Uqed%2B0kLhtQaDjQ6FEEZxp4ORUAejnLAvh2qBV%2FTiUM1ifhunUbg7m6n0coREUDPWns7zQgMpNppMEn0Bp2m7QKQMqHR5TQWmLrIvs0YApoxRHEzhuB0%2B3dOU1WWEo%2FpdWmCXmPbdkfGdgCLTGAV1bexZUXAS4zd1qS6LOWAvouxL5Zrt5TVAZYLxDYGva7E01pDdGdxOBBcV9S3xTssJjEWd7MqcydOi6bIK3caxERCirF14Qn5etUwgQvPkiy7D2OfX92gy14XIQ%2BzZUc3HU%2B6WMSpO38WHrE7Al2dEWiAoovsC9sGcCOiuOgiuFI%2FSasmcFoS%2FWExytLP59kA0NRDFmZF%2B2zuP9D4L%2F5cd5QWXYJ1j42Hc61xgNju9di6e5fAErZk0YslW7PYX%2B%2BS4Iq4WGlWrXVKD38hEmLEJA1lpT03%2B2X15utMc0RPfCfIEq0gawJuwdk7zYHNc8Vpjo3r1kmx9lDWFLxIklmx4mYcJSt%2BTraklIOs5nzH8pzjZgfLlW2PE76lpINld1Fmak952kZj6UbaeGYwP7pw2msbjTbInRy4HbDvaMSV6kGv3yaA%2FnMc3XMozjnFpr0SD0XyuMzDJK5lmWtoTGm%2BSuNXsE4CY6JEuYox8RDaKGLG3I2JWjMUG2QoLmzct8ZEkKG4itk7Gy%2Fl%2B7asNucvkyysArGo4%2BpVW1XQHeuPRNdrKNAzdcehcIX%2B49Bx4aKK7fvRuozR1nnLSGveAjhODzIsrWMU1KKu4k0Uzptodeo1NswtPVjptW6nwB36Yo2UKmO%2FrLJ5g61OqOB9wxIO5MC6pG9LdfnSkX5bnXrpnJ2Gam1xgOiq6Rynw%2BWSTSx2FZKAXkunMbQCOkiw9%2B50wj1iql0G9%2BbGEfXj1RJ5jurMGaZHrqSPKXvnVX%2BJc6eLRw3Pa4bYllXpjVXKzcAbbhLsHtPp1jRg6UvaSHmA4u6%2B87YFlig5qtNpzJMc8u41AzIMku0nSllAB1MOnXSeAxqxAA0Gb6TrDMwyku0Ll3Wdzd66zmJCeNMtTjHh7kZTrekNXP4x2pdANEHhO1JMILomcpqzIhAHoMmpOdshlgkYe8OwPclW6pFkJ97v7PtnIaeqj%2BkMG6w95wpNoiC5EWC%2FMxxLP9LGFcIyAb1TrzVZCF9SpXo9rotpia2MPt6BrJ%2FQJ1ZzT6SxLjjqQephV%2BitLnFV7ZLss7EmcHp3IGpd4YzCB5l1386agd47t3cgssPNS7XL0zevJrfO%2Fwc%3D

**Comment by PatrickDuncan** [comment]
@VictorCarri can you please add this to the wiki and update as time goes by?

**Comment by PatrickDuncan** [comment]
Closing because the work is continuous
