### ISSUE TITLE
Expand Vocal Pitch and BPM Research

### ISSUE THREAD

**Issue by PatrickDuncan** [PatrickDuncan/cleansio#57]
Please add at least 3 more songs to https://github.com/PatrickDuncan/cleansio/wiki/Beats-Per-Minute-(BPM)-Research and https://github.com/PatrickDuncan/cleansio/wiki/Vocal-Pitch-Research

**Comment by levin-noro** [comment]
Added more songs to BPM Research. Concluded that BPM did not significantly impact lyrical transcription accuracy.
