### ISSUE TITLE
User List of Explicits

### ISSUE THREAD

**Issue by VictorCarri** [PatrickDuncan/cleansio#66]
We shouldn't use a hard-coded list. Please add code which loads in an encrypted YAML list of swear words before the rest of the program runs.

- [x] The file should either be in Cleansio's directory (gitignore the content) or they should provide the path to the YAML
- [x] There should be a sample YAML as a reference to the user
- [ ] Pass the file through the command-line

**Comment by VictorCarri** [comment]
Note: the user need not provide an encrypted list, but we might want to provide an option to encrypt it for them.

**Comment by PatrickDuncan** [comment]
- [ ] The file should either be in Cleansio's directory (gitignore the content) or they should provide the path to the YAML
- [ ] There should be a sample YAML as a reference to the user
