### ISSUE TITLE
Internal List of Explicits

### ISSUE THREAD

**Issue by VictorCarri** [PatrickDuncan/cleansio#67]
We need to have an internal list of explicit words in case the user doesn't choose to provide their own list. This should be an encrypted YAML file.

- [x] Reference a reliable source for explicit words
- [x] Use a YAML file to list the explicits
- [x] Either encrypt the contents of the entire file or each explicit
     - _We're encrypting to avoid curse words to our repo_

[Crypto Suggestion](https://docs.python-guide.org/scenarios/crypto/)

**Comment by levin-noro** [comment]
References:
1. http://www.bannedwordlist.com
2. https://www.freewebheaders.com/full-list-of-bad-words-banned-by-google/
